<?php $d = $doc; ?>
<div class="erp-page-head"><h5 class="mb-0 font-monospace" data-testid="pr-no"><?= e($d['pr_no']) ?></h5><a class="btn btn-sm btn-link" href="<?= site_url('purchasing/requests') ?>">&larr; Daftar</a></div>
<?php $this->load->view('partials/workflow_panel', ['doc' => $d, 'base' => 'purchasing/requests', 'editUrl' => "purchasing/requests/{$d['id']}/edit",
    'perms' => ['submit' => 'purchasing.pr.edit', 'edit' => 'purchasing.pr.edit', 'approve' => 'purchasing.pr.approve', 'reject' => 'purchasing.pr.approve', 'cancel' => 'purchasing.pr.cancel', 'close' => 'purchasing.pr.approve']]); ?>
<div class="card erp-card mb-3"><div class="card-body"><dl class="row small mb-0"><dt class="col-2">Tanggal</dt><dd class="col-4"><?= fmt_date($d['request_date']) ?></dd><dt class="col-2">Dibutuhkan</dt><dd class="col-4"><?= fmt_date($d['required_date']) ?></dd>
<dt class="col-2">Estimasi</dt><dd class="col-4"><?= fmt_idr($d['total_estimated']) ?></dd><dt class="col-2">Catatan</dt><dd class="col-4"><?= e($d['notes']) ?></dd>
<?php if ($d['rejection_reason']): ?><dt class="col-2 text-danger">Alasan tolak</dt><dd class="col-10 text-danger"><?= e($d['rejection_reason']) ?></dd><?php endif; ?></dl></div></div>
<?php if (in_array($d['status'], ['APPROVED'], true) && can('purchasing.po.create')): ?><a class="btn btn-sm btn-outline-primary mb-3" href="<?= site_url('purchasing/orders/create?pr_id=' . $d['id']) ?>" data-testid="pr-to-po"><i class="bi bi-arrow-right-circle me-1"></i>Buat PO dari PR ini</a><?php endif; ?>
<div class="card erp-card"><table class="table table-sm erp-table mb-0" data-testid="pr-items-table"><thead><tr><th>#</th><th>Produk</th><th class="text-end">Qty</th><th class="text-end">Est. Harga</th><th>Catatan</th></tr></thead><tbody>
<?php foreach ($d['items'] as $i): ?><tr><td><?= $i['line_no'] ?></td><td><?= e($i['product_name']) ?><br><small class="text-muted font-monospace"><?= e($i['sku']) ?></small></td><td class="text-end"><?= fmt_num($i['qty'], 0) ?></td><td class="text-end small"><?= fmt_idr($i['estimated_price']) ?></td><td class="small text-muted"><?= e($i['notes']) ?></td></tr><?php endforeach; ?></tbody></table></div>
