<?php $d = $doc ?? []; $items = old('items', $d['items'] ?? []); $errs = $this->session->flashdata('errors') ?: []; ?>
<form method="post" data-testid="gr-form" class="erp-doc-form"><?= csrf_field() ?>
<div class="card erp-card mb-3"><div class="card-body row g-2">
    <div class="col-md-4"><label class="form-label">Supplier *</label><select class="form-select form-select-sm <?= isset($errs['supplier_id']) ? 'is-invalid' : '' ?>" name="supplier_id" required data-testid="gr-supplier"><option value="">—</option><?php foreach ($suppliers as $s): ?><option value="<?= $s['id'] ?>" <?= (string) old('supplier_id', $d['supplier_id'] ?? '') === (string) $s['id'] ? 'selected' : '' ?>><?= e($s['name']) ?></option><?php endforeach; ?></select><div class="invalid-feedback"><?= e($errs['supplier_id'] ?? '') ?></div></div>
    <div class="col-md-3"><label class="form-label">Gudang Penerima *</label><select class="form-select form-select-sm" name="warehouse_id" id="warehouseSelect" required data-testid="gr-warehouse"><option value="">—</option><?php foreach ($warehouses as $w): ?><option value="<?= $w['id'] ?>" <?= (string) old('warehouse_id', $d['warehouse_id'] ?? '') === (string) $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-3"><label class="form-label">Referensi PO</label><select class="form-select form-select-sm" name="po_id" data-testid="gr-po"><option value="">— (tanpa PO)</option><?php foreach ($orders as $o): ?><option value="<?= $o['id'] ?>" <?= (string) old('po_id', $d['po_id'] ?? $this->input->get('po_id')) === (string) $o['id'] ? 'selected' : '' ?>><?= e($o['po_no']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-2"><label class="form-label">Tanggal Terima *</label><input class="form-control form-control-sm" type="date" name="receipt_date" value="<?= e(old('receipt_date', $d['receipt_date'] ?? date('Y-m-d'))) ?>" required data-testid="gr-date"></div>
    <div class="col-md-3"><label class="form-label">No. Surat Jalan</label><input class="form-control form-control-sm" name="supplier_do_no" value="<?= e(old('supplier_do_no', $d['supplier_do_no'] ?? '')) ?>"></div>
    <div class="col-md-3"><label class="form-label">No. Faktur Supplier</label><input class="form-control form-control-sm" name="supplier_invoice_no" value="<?= e(old('supplier_invoice_no', $d['supplier_invoice_no'] ?? '')) ?>"></div>
    <div class="col-md-6"><label class="form-label">Catatan</label><input class="form-control form-control-sm" name="notes" value="<?= e(old('notes', $d['notes'] ?? '')) ?>"></div>
</div></div>
<div class="card erp-card mb-3"><div class="card-header d-flex justify-content-between"><span>Item Diterima</span><small class="text-muted">Produk farmasi WAJIB nomor batch + kedaluwarsa. Hasil inspeksi menentukan kondisi stok.</small></div>
<div class="table-responsive"><table class="table table-sm erp-table mb-0 erp-items" id="itemsTable" data-testid="gr-items"><thead><tr><th style="width:22%">Produk *</th><th>Batch</th><th>Kedaluwarsa</th><th class="text-end">Qty *</th><th class="text-end">Harga</th><th>Lokasi</th><th>Inspeksi</th><th></th></tr></thead><tbody>
<?php foreach (array_merge($items, [[]]) as $i => $it): ?><tr>
    <td><input type="hidden" name="items[<?= $i ?>][po_item_id]" value="<?= e($it['po_item_id'] ?? '') ?>"><input type="hidden" name="items[<?= $i ?>][product_id]" value="<?= e($it['product_id'] ?? '') ?>" class="js-product-id"><input class="form-control form-control-sm js-product-search" value="<?= e(isset($it['product_name']) ? $it['sku'] . ' — ' . $it['product_name'] : ($it['product_label'] ?? '')) ?>" placeholder="Cari produk…" autocomplete="off" data-testid="gr-item-product-<?= $i ?>"><input type="hidden" name="items[<?= $i ?>][product_label]" class="js-product-label"></td>
    <td><input class="form-control form-control-sm" name="items[<?= $i ?>][batch_no]" value="<?= e($it['batch_no'] ?? '') ?>" data-testid="gr-item-batch-<?= $i ?>"></td>
    <td><input class="form-control form-control-sm" type="date" name="items[<?= $i ?>][expiry_date]" value="<?= e($it['expiry_date'] ?? '') ?>" data-testid="gr-item-expiry-<?= $i ?>"></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][qty_received]" value="<?= e($it['qty_received'] ?? '') ?>" inputmode="decimal" data-testid="gr-item-qty-<?= $i ?>"></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][unit_cost]" value="<?= e($it['unit_cost'] ?? '') ?>" inputmode="decimal"></td>
    <td><input class="form-control form-control-sm" name="items[<?= $i ?>][location_id]" value="<?= e($it['location_id'] ?? '') ?>" placeholder="ID lokasi (opsional)"></td>
    <td><select class="form-select form-select-sm" name="items[<?= $i ?>][inspection_result]" data-testid="gr-item-inspection-<?= $i ?>"><?php foreach (['ACCEPTED' => 'Diterima (GOOD)', 'QUARANTINE' => 'Karantina', 'REJECTED' => 'Ditolak'] as $k => $lbl): ?><option value="<?= $k ?>" <?= ($it['inspection_result'] ?? 'ACCEPTED') === $k ? 'selected' : '' ?>><?= $lbl ?></option><?php endforeach; ?></select></td>
    <td><button type="button" class="btn btn-xs btn-outline-danger row-remove"><i class="bi bi-x"></i></button></td></tr><?php endforeach; ?>
</tbody></table></div><div class="p-2"><button type="button" class="btn btn-xs btn-outline-secondary" data-add-row="#itemsTable" data-testid="gr-add-row"><i class="bi bi-plus"></i> Tambah baris</button><?php if (isset($errs['items'])): ?><span class="text-danger small ms-2"><?= e($errs['items']) ?></span><?php endif; ?></div></div>
<button class="btn btn-primary" data-testid="gr-save"><i class="bi bi-save me-1"></i>Simpan sebagai Draft</button> <a class="btn btn-link" href="<?= site_url('purchasing/receipts') ?>">Batal</a>
</form>
