<?php $d = $doc; ?>
<div class="erp-page-head"><h5 class="mb-0 font-monospace" data-testid="gr-no"><?= e($d['gr_no']) ?></h5><a class="btn btn-sm btn-link" href="<?= site_url('purchasing/receipts') ?>">&larr; Daftar</a></div>
<?php $this->load->view('partials/workflow_panel', ['doc' => $d, 'base' => 'purchasing/receipts', 'editUrl' => "purchasing/receipts/{$d['id']}/edit",
    'perms' => ['submit' => 'purchasing.gr.edit', 'edit' => 'purchasing.gr.edit', 'approve' => 'purchasing.gr.approve', 'reject' => 'purchasing.gr.approve', 'cancel' => 'purchasing.gr.cancel', 'post' => 'purchasing.gr.post', 'reverse' => 'purchasing.gr.post']]); ?>
<div class="card erp-card mb-3"><div class="card-body"><dl class="row small mb-0">
<dt class="col-2">Supplier</dt><dd class="col-4"><?= e($d['supplier']['name'] ?? '-') ?></dd><dt class="col-2">Gudang</dt><dd class="col-4"><?= e($d['warehouse']['name'] ?? '-') ?></dd>
<dt class="col-2">Tanggal</dt><dd class="col-4"><?= fmt_date($d['receipt_date']) ?></dd><dt class="col-2">No. Surat Jalan</dt><dd class="col-4"><?= e($d['supplier_do_no'] ?: '-') ?></dd>
<dt class="col-2">No. Faktur</dt><dd class="col-4"><?= e($d['supplier_invoice_no'] ?: '-') ?></dd><dt class="col-2">Mutasi stok</dt><dd class="col-4"><?= $d['movement_id'] ? '<a href="' . site_url('inventory/movements/' . $d['movement_id']) . '" data-testid="gr-movement-link">#' . $d['movement_id'] . '</a>' : '-' ?><?= $d['reversal_movement_id'] ? ' · balik #' . $d['reversal_movement_id'] : '' ?></dd>
<dt class="col-2">Nilai</dt><dd class="col-4"><?= fmt_idr($d['total_value']) ?></dd><dt class="col-2">Catatan</dt><dd class="col-4"><?= e($d['notes']) ?></dd>
<?php if ($d['rejection_reason']): ?><dt class="col-2 text-danger">Alasan tolak</dt><dd class="col-10 text-danger"><?= e($d['rejection_reason']) ?></dd><?php endif; ?></dl></div></div>
<?php if ($d['status'] === 'POSTED' && can('purchasing.ap.create')): ?><form method="post" action="<?= site_url('purchasing/ap-invoices/from-gr/' . $d['id']) ?>" class="mb-3 needs-confirm" data-confirm="Buat tagihan AP dari GR ini?"><?= csrf_field() ?><button class="btn btn-sm btn-outline-primary" data-testid="gr-to-ap"><i class="bi bi-receipt me-1"></i>Buat Tagihan AP</button></form><?php endif; ?>
<div class="card erp-card"><table class="table table-sm erp-table mb-0" data-testid="gr-items-table"><thead><tr><th>#</th><th>Produk</th><th>Batch / ED</th><th class="text-end">Qty</th><th class="text-end">Harga</th><th>Lokasi</th><th>Kondisi</th><th>Inspeksi</th></tr></thead><tbody>
<?php foreach ($d['items'] as $i): ?><tr><td><?= $i['line_no'] ?></td><td><?= e($i['product_name']) ?><br><small class="text-muted font-monospace"><?= e($i['sku']) ?></small></td><td class="small font-monospace"><?= e($i['batch_no'] ?: '-') ?> <span class="text-muted"><?= fmt_date($i['expiry_date']) ?></span></td><td class="text-end"><?= fmt_num($i['qty_received'], 0) ?></td><td class="text-end small"><?= fmt_idr($i['unit_cost']) ?></td><td class="small"><?= e($i['location_code'] ?? '-') ?></td><td><?= status_badge($i['condition_code']) ?></td><td class="small"><?= e($i['inspection_result']) ?></td></tr><?php endforeach; ?></tbody></table></div>
