<?php $s = $sale; ?>
<div class="erp-page-head"><h5 class="mb-0 font-monospace" data-testid="sale-no"><?= e($s['sale_no']) ?></h5><a class="btn btn-sm btn-link" href="<?= site_url('sales/pos') ?>">&larr; Daftar</a></div>
<div class="card erp-card mb-3"><div class="card-body"><dl class="row small mb-0">
<dt class="col-3">Waktu</dt><dd class="col-3"><?= fmt_dt($s['sale_datetime']) ?></dd><dt class="col-3">Status</dt><dd class="col-3"><?= status_badge($s['status']) ?></dd>
<dt class="col-3">Pelanggan</dt><dd class="col-3"><?= e($s['customer']['name'] ?? 'Umum') ?></dd><dt class="col-3">Mutasi stok</dt><dd class="col-3"><?= $s['movement_id'] ? '<a href="' . site_url('inventory/movements/' . $s['movement_id']) . '">#' . $s['movement_id'] . '</a>' : '-' ?><?= $s['void_movement_id'] ? ' · void #' . $s['void_movement_id'] : '' ?></dd>
<?php if ($s['void_reason']): ?><dt class="col-3 text-danger">Alasan void</dt><dd class="col-9 text-danger"><?= e($s['void_reason']) ?></dd><?php endif; ?></dl></div></div>
<?php if ($s['status'] === 'PAID' && can('sales.pos.void')): ?><form method="post" action="<?= site_url('sales/pos/' . $s['id'] . '/void') ?>" class="d-inline-flex gap-1 mb-3 needs-confirm" data-confirm="Void transaksi ini? Stok akan dikembalikan."><?= csrf_field() ?><input class="form-control form-control-sm" name="reason" placeholder="Alasan void" style="width:240px" data-testid="sale-void-reason"><button class="btn btn-sm btn-outline-danger" data-testid="sale-void-btn"><i class="bi bi-x-octagon me-1"></i>Void</button></form><?php endif; ?>
<div class="card erp-card mb-3"><table class="table table-sm erp-table mb-0" data-testid="sale-items-table"><thead><tr><th>#</th><th>Produk</th><th>Batch/ED</th><th class="text-end">Qty</th><th class="text-end">Harga</th><th class="text-end">Total</th></tr></thead><tbody>
<?php foreach ($s['items'] as $i): ?><tr><td><?= $i['line_no'] ?></td><td><?= e($i['product_name']) ?><br><small class="text-muted font-monospace"><?= e($i['sku']) ?></small></td><td class="small font-monospace"><?= e($i['batch_no'] ?? '-') ?> <span class="text-muted"><?= fmt_date($i['expiry_date'] ?? null) ?></span></td><td class="text-end"><?= fmt_num($i['qty'], 0) ?></td><td class="text-end small"><?= fmt_idr($i['unit_price']) ?></td><td class="text-end"><?= fmt_idr($i['line_total']) ?></td></tr><?php endforeach; ?></tbody>
<tfoot><tr><th colspan="5" class="text-end">Subtotal</th><th class="text-end"><?= fmt_idr($s['subtotal']) ?></th></tr><tr><th colspan="5" class="text-end">Diskon</th><th class="text-end">-<?= fmt_idr($s['discount_total']) ?></th></tr><tr><th colspan="5" class="text-end">Pajak</th><th class="text-end"><?= fmt_idr($s['tax_total']) ?></th></tr><tr><th colspan="5" class="text-end">Grand Total</th><th class="text-end" data-testid="sale-grand-total"><?= fmt_idr($s['grand_total']) ?></th></tr><tr><th colspan="5" class="text-end">Dibayar</th><th class="text-end"><?= fmt_idr($s['paid_total']) ?></th></tr><tr><th colspan="5" class="text-end">Kembalian</th><th class="text-end" data-testid="sale-change"><?= fmt_idr($s['change_amount']) ?></th></tr></tfoot></table></div>
<div class="card erp-card"><div class="card-header py-1 small fw-semibold">Pembayaran</div><table class="table table-sm erp-table mb-0"><tbody><?php foreach ($s['payments'] as $p): ?><tr><td class="small"><?= e($p['method']) ?></td><td class="small text-muted"><?= e($p['reference']) ?></td><td class="text-end"><?= fmt_idr($p['amount']) ?></td></tr><?php endforeach; ?></tbody></table></div>
