<div class="erp-page-head"><form class="erp-filter" method="get" data-testid="stock-filter"><input class="form-control form-control-sm" name="q" value="<?= e($_GET['q'] ?? '') ?>" placeholder="Produk / SKU / batch" autofocus>
    <select class="form-select form-select-sm" name="warehouse_id"><option value="">Semua gudang</option><?php foreach ($warehouses as $w): ?><option value="<?= $w['id'] ?>" <?= ($_GET['warehouse_id'] ?? '') == $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select>
    <select class="form-select form-select-sm" name="condition_code"><option value="">Semua kondisi</option><?php foreach (['GOOD', 'DAMAGED', 'QUARANTINE', 'EXPIRED'] as $c): ?><option <?= ($_GET['condition_code'] ?? '') === $c ? 'selected' : '' ?>><?= $c ?></option><?php endforeach; ?></select>
    <input class="form-control form-control-sm" type="number" name="expiring_days" value="<?= e($_GET['expiring_days'] ?? (!empty($expiry_mode) ? 90 : '')) ?>" placeholder="ED ≤ hari" style="width:110px">
    <label class="small"><input type="checkbox" class="form-check-input" name="include_zero" value="1" <?= !empty($_GET['include_zero']) ? 'checked' : '' ?>> saldo 0</label><button class="btn btn-sm btn-outline-secondary">Filter</button></form></div>
<div class="card erp-card"><div class="table-responsive"><table class="table table-sm table-hover erp-table mb-0" data-testid="stock-table">
<thead><tr><th><?= sort_link('product_name', 'Produk') ?></th><th><?= sort_link('warehouse_name', 'Gudang') ?></th><th>Lokasi</th><th>Batch</th><th><?= sort_link('expiry_date', 'ED') ?></th><th>Kondisi</th><th class="text-end"><?= sort_link('qty_on_hand', 'On Hand') ?></th><th class="text-end">Reserved</th><th class="text-end">Tersedia</th><th class="text-end">Nilai</th></tr></thead><tbody>
<?php foreach ($page->items as $r): $exp = $r['days_to_expiry'] !== null ? (int) $r['days_to_expiry'] : null; ?><tr data-testid="stock-row-<?= $r['id'] ?>">
    <td><a href="<?= site_url('inventory/stock/card/' . $r['product_id']) ?>"><?= e($r['product_name']) ?></a><br><small class="text-muted font-monospace"><?= e($r['sku']) ?></small></td><td class="small"><?= e($r['warehouse_name']) ?></td><td class="small font-monospace"><?= e($r['location_code']) ?></td><td class="font-monospace small"><?= e($r['batch_no'] ?? '-') ?></td>
    <td class="small text-nowrap <?= $exp !== null && $exp < 0 ? 'text-danger fw-semibold' : ($exp !== null && $exp <= 90 ? 'text-warning fw-semibold' : '') ?>"><?= fmt_date($r['expiry_date']) ?><?= $exp !== null ? '<br><span class="text-muted">' . ($exp < 0 ? 'ED ' . abs($exp) . ' hari lalu' : $exp . ' hari') . '</span>' : '' ?></td>
    <td><?= status_badge($r['condition_code']) ?></td><td class="text-end"><?= fmt_num($r['qty_on_hand'], 0) ?></td><td class="text-end text-muted"><?= fmt_num($r['qty_reserved'], 0) ?></td><td class="text-end fw-semibold"><?= fmt_num($r['available'], 0) ?></td><td class="text-end small"><?= fmt_idr($r['qty_on_hand'] * $r['avg_cost']) ?></td>
</tr><?php endforeach; ?><?php if (!$page->items): ?><tr><td colspan="10" class="text-center text-muted py-4">Tidak ada data</td></tr><?php endif; ?>
</tbody></table></div><div class="card-footer py-1"><?php $this->load->view('partials/pagination', ['page' => $page]); ?></div></div>
