<div class="erp-page-head"><form class="erp-filter" method="get"><input class="form-control form-control-sm" name="q" value="<?= e($_GET['q'] ?? '') ?>" placeholder="Batch / produk">
    <select class="form-select form-select-sm" name="status"><option value="">Semua status</option><?php foreach (['ACTIVE', 'QUARANTINE', 'RECALLED', 'EXPIRED', 'DEPLETED'] as $s): ?><option <?= ($_GET['status'] ?? '') === $s ? 'selected' : '' ?>><?= $s ?></option><?php endforeach; ?></select>
    <input class="form-control form-control-sm" type="number" name="expiring_days" value="<?= e($_GET['expiring_days'] ?? '') ?>" placeholder="ED ≤ hari" style="width:110px"><label class="small"><input type="checkbox" class="form-check-input" name="with_stock" value="1" <?= !empty($_GET['with_stock']) ? 'checked' : '' ?>> ada stok</label><button class="btn btn-sm btn-outline-secondary">Filter</button></form></div>
<div class="card erp-card"><div class="table-responsive"><table class="table table-sm table-hover erp-table mb-0" data-testid="batches-table"><thead><tr><th><?= sort_link('batch_no', 'Batch') ?></th><th><?= sort_link('product_name', 'Produk') ?></th><th>Mfg</th><th><?= sort_link('expiry_date', 'ED') ?></th><th>Sumber</th><th class="text-end">Stok</th><th class="text-end">Cost</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach ($page->items as $b): $d = $b['days_to_expiry']; ?><tr data-testid="batch-row-<?= $b['id'] ?>"><td class="font-monospace"><?= e($b['batch_no']) ?></td><td><?= e($b['product_name']) ?><br><small class="text-muted"><?= e($b['sku']) ?></small></td><td class="small"><?= fmt_date($b['manufacture_date']) ?></td>
<td class="small <?= $d !== null && $d < 0 ? 'text-danger fw-semibold' : ($d !== null && $d <= 90 ? 'text-warning fw-semibold' : '') ?>"><?= fmt_date($b['expiry_date']) ?><?= $d !== null ? "<br><span class='text-muted'>" . ($d < 0 ? 'lewat ' . abs($d) . ' hr' : $d . ' hari') . '</span>' : '' ?></td><td class="small font-monospace"><?= e($b['source_ref_no']) ?></td>
<td class="text-end"><?= fmt_num($b['qty_on_hand'], 0) ?></td><td class="text-end small"><?= fmt_idr($b['unit_cost']) ?></td><td><?= status_badge($b['status']) ?></td>
<td class="text-end"><?php if (can('inventory.batch.quarantine') && $b['qty_on_hand'] > 0): $act = $b['status'] === 'QUARANTINE' ? 'release' : 'quarantine'; ?>
<form method="post" action="<?= site_url("inventory/batches/{$b['id']}/$act") ?>" class="d-inline-flex gap-1 needs-confirm" data-confirm="<?= $act === 'quarantine' ? 'Karantina seluruh stok batch ini?' : 'Lepas batch dari karantina?' ?>"><?= csrf_field() ?><input class="form-control form-control-sm" name="reason" placeholder="Alasan" required style="width:140px" data-testid="batch-reason-<?= $b['id'] ?>"><button class="btn btn-xs btn-outline-<?= $act === 'quarantine' ? 'warning' : 'success' ?>" data-testid="batch-<?= $act ?>-<?= $b['id'] ?>"><?= $act === 'quarantine' ? 'Karantina' : 'Lepas' ?></button></form><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div><div class="card-footer py-1"><?php $this->load->view('partials/pagination', ['page' => $page]); ?></div></div>
