<?php if (isset($product)): ?><h6 class="mb-2" data-testid="card-product"><a href="<?= site_url('master/products/' . $product['id']) ?>"><?= e($product['name']) ?></a> <span class="font-monospace text-muted small"><?= e($product['sku']) ?></span></h6><?php endif; ?>
<div class="erp-page-head"><form class="erp-filter" method="get" data-testid="ledger-filter">
    <?php if (!isset($product)): ?><input class="form-control form-control-sm" name="product_id" value="<?= e($_GET['product_id'] ?? '') ?>" placeholder="ID produk" style="width:110px"><?php endif; ?>
    <select class="form-select form-select-sm" name="warehouse_id"><option value="">Semua gudang</option><?php foreach ($warehouses as $w): ?><option value="<?= $w['id'] ?>" <?= ($_GET['warehouse_id'] ?? '') == $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select>
    <input class="form-control form-control-sm" type="date" name="date_from" value="<?= e($_GET['date_from'] ?? '') ?>"><input class="form-control form-control-sm" type="date" name="date_to" value="<?= e($_GET['date_to'] ?? '') ?>"><button class="btn btn-sm btn-outline-secondary">Filter</button></form></div>
<div class="card erp-card"><div class="table-responsive"><table class="table table-sm erp-table mb-0" data-testid="ledger-table">
<thead><tr><th>Waktu</th><th>No. Mutasi</th><th>Tipe</th><th>Referensi</th><?php if (!isset($product)): ?><th>Produk</th><?php endif; ?><th>Gudang</th><th>Batch / ED</th><th class="text-end">Masuk</th><th class="text-end">Keluar</th><th class="text-end">Saldo</th><th class="text-end">Harga</th><th>Oleh</th></tr></thead><tbody>
<?php foreach ($page->items as $r): ?><tr><td class="small text-nowrap"><?= fmt_date($r['posted_at'], 'd/m/Y H:i:s') ?></td><td><a class="font-monospace small" href="<?= site_url('inventory/movements/' . $r['movement_id']) ?>"><?= e($r['movement_no']) ?></a></td><td class="small"><?= e($r['movement_type']) ?></td><td class="small font-monospace"><?= e($r['ref_no']) ?></td>
<?php if (!isset($product)): ?><td class="small"><?= e($r['product_name']) ?><br><span class="text-muted"><?= e($r['sku']) ?></span></td><?php endif; ?><td class="small"><?= e($r['warehouse_name']) ?></td><td class="small font-monospace"><?= e($r['batch_no'] ?? '-') ?><br><span class="text-muted"><?= fmt_date($r['expiry_date']) ?></span></td>
<td class="text-end text-success"><?= $r['qty_in'] > 0 ? fmt_num($r['qty_in'], 0) : '' ?></td><td class="text-end text-danger"><?= $r['qty_out'] > 0 ? fmt_num($r['qty_out'], 0) : '' ?></td><td class="text-end fw-semibold"><?= fmt_num($r['balance_after'], 0) ?></td><td class="text-end small"><?= fmt_idr($r['unit_cost']) ?></td><td class="small"><?= e($r['posted_by_name']) ?></td></tr><?php endforeach; ?>
<?php if (!$page->items): ?><tr><td colspan="12" class="text-center text-muted py-4">Belum ada mutasi</td></tr><?php endif; ?>
</tbody></table></div><div class="card-footer py-1"><?php $this->load->view('partials/pagination', ['page' => $page]); ?></div></div>
