<?php $m = $movement; ?>
<div class="card erp-card mb-3" data-testid="movement-header"><div class="card-body d-flex flex-wrap justify-content-between gap-3">
<dl class="row small mb-0 flex-grow-1"><dt class="col-3">No. Mutasi</dt><dd class="col-9 font-monospace"><?= e($m['movement_no']) ?> <?= status_badge($m['status']) ?></dd><dt class="col-3">Tipe</dt><dd class="col-9"><?= e($types[$m['movement_type']]['label'] ?? $m['movement_type']) ?></dd>
<dt class="col-3">Referensi</dt><dd class="col-9 font-monospace"><?= e($m['ref_type']) ?> <?= e($m['ref_no']) ?></dd><dt class="col-3">Diposting</dt><dd class="col-9"><?= fmt_date($m['posted_at'], 'd/m/Y H:i:s') ?> oleh <?= e($m['posted_by_name']) ?></dd>
<?php if ($m['reversal_of_id']): ?><dt class="col-3">Pembalikan dari</dt><dd class="col-9"><a href="<?= site_url('inventory/movements/' . $m['reversal_of_id']) ?>">#<?= $m['reversal_of_id'] ?></a></dd><?php endif; ?>
<?php if ($m['reversed_by_id']): ?><dt class="col-3">Dibalik oleh</dt><dd class="col-9"><a href="<?= site_url('inventory/movements/' . $m['reversed_by_id']) ?>">#<?= $m['reversed_by_id'] ?></a></dd><?php endif; ?>
<dt class="col-3">Catatan</dt><dd class="col-9"><?= e($m['notes']) ?></dd></dl>
<?php if ($m['status'] === 'POSTED' && $m['movement_type'] !== 'REVERSAL' && can('inventory.movement.reverse')): ?>
<form method="post" action="<?= site_url("inventory/movements/{$m['id']}/reverse") ?>" class="needs-confirm border rounded p-2" style="min-width:280px" data-confirm="Membuat mutasi pembalikan (compensating). Mutasi asli tetap tersimpan. Lanjutkan?" data-testid="reverse-form"><?= csrf_field() ?>
<div class="small fw-semibold mb-1">Balik Mutasi</div><select class="form-select form-select-sm mb-1" name="reason_code_id"><option value="">Kode alasan…</option><?php foreach ($reasons as $r): ?><option value="<?= $r['id'] ?>"><?= e($r['name']) ?></option><?php endforeach; ?></select>
<input class="form-control form-control-sm mb-1" name="reason" placeholder="Alasan (wajib)" required data-testid="reverse-reason"><button class="btn btn-sm btn-outline-danger w-100" data-testid="reverse-submit"><i class="bi bi-arrow-counterclockwise me-1"></i>Buat Pembalikan</button></form><?php endif; ?>
</div></div>
<div class="card erp-card"><table class="table table-sm erp-table mb-0" data-testid="movement-items"><thead><tr><th>#</th><th>Produk</th><th>Gudang / Lokasi</th><th>Batch</th><th>ED</th><th>Kondisi</th><th class="text-end">Qty</th><th class="text-end">Harga</th><th class="text-end">Nilai</th></tr></thead><tbody>
<?php foreach ($items as $i): ?><tr><td><?= $i['line_no'] ?></td><td><?= e($i['product_name']) ?><br><small class="text-muted font-monospace"><?= e($i['sku']) ?></small></td><td class="small"><?= e($i['warehouse_name']) ?> / <?= e($i['location_code']) ?></td><td class="font-monospace small"><?= e($i['batch_no'] ?? '-') ?></td><td class="small"><?= fmt_date($i['expiry_date']) ?></td><td><?= status_badge($i['condition_code']) ?></td>
<td class="text-end fw-semibold <?= $i['qty'] < 0 ? 'text-danger' : 'text-success' ?>"><?= ($i['qty'] > 0 ? '+' : '') . fmt_num($i['qty'], 0) ?></td><td class="text-end small"><?= fmt_idr($i['unit_cost']) ?></td><td class="text-end small"><?= fmt_idr($i['qty'] * $i['unit_cost']) ?></td></tr><?php endforeach; ?></tbody></table></div>
