<div class="erp-page-head">
    <form class="erp-filter" method="get" data-testid="products-filter"><input class="form-control form-control-sm" name="q" value="<?= e($_GET['q'] ?? '') ?>" placeholder="Cari nama / SKU / barcode / generik" autofocus>
        <select class="form-select form-select-sm" name="category_id"><option value="">Semua kategori</option><?php foreach ($refs['categories'] as $c): ?><option value="<?= $c['id'] ?>" <?= ($_GET['category_id'] ?? '') == $c['id'] ? 'selected' : '' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select>
        <select class="form-select form-select-sm" name="status"><option value="">Semua status</option><?php foreach (['ACTIVE', 'INACTIVE', 'DISCONTINUED'] as $s): ?><option <?= ($_GET['status'] ?? '') === $s ? 'selected' : '' ?>><?= $s ?></option><?php endforeach; ?></select>
        <label class="form-check-label small"><input type="checkbox" class="form-check-input" name="requires_prescription" value="1" <?= !empty($_GET['requires_prescription']) ? 'checked' : '' ?>> Resep</label>
        <label class="form-check-label small"><input type="checkbox" class="form-check-input" name="is_controlled" value="1" <?= !empty($_GET['is_controlled']) ? 'checked' : '' ?>> Terkontrol</label>
        <button class="btn btn-sm btn-outline-secondary">Filter</button></form>
    <?php if (can('master.product.create')): ?><a class="btn btn-sm btn-primary" href="<?= site_url('master/products/create') ?>" data-testid="product-create-btn"><i class="bi bi-plus-lg me-1"></i>Produk Baru</a><?php endif; ?>
</div>
<div class="card erp-card"><div class="table-responsive"><table class="table table-sm table-hover erp-table mb-0" data-testid="products-table">
<thead><tr><th><?= sort_link('sku', 'SKU') ?></th><th><?= sort_link('name', 'Nama') ?></th><th>Kekuatan / Bentuk</th><th>Kategori</th><th>Golongan</th><th class="text-end"><?= sort_link('qty_on_hand', 'Stok') ?></th><th class="text-end"><?= sort_link('selling_price', 'Harga Jual') ?></th><th>Flag</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach ($page->items as $p): ?><tr data-testid="product-row-<?= $p['id'] ?>">
    <td class="font-monospace small"><?= e($p['sku']) ?><br><span class="text-muted"><?= e($p['barcode']) ?></span></td><td><a href="<?= site_url('master/products/' . $p['id']) ?>"><?= e($p['name']) ?></a><br><small class="text-muted"><?= e($p['generic_name']) ?></small></td>
    <td class="small"><?= e($p['strength']) ?> <?= e($p['dosage_form']) ?></td><td class="small"><?= e($p['category_name']) ?></td><td class="small"><?= e($p['classification_name']) ?></td>
    <td class="text-end <?= $p['qty_on_hand'] <= $p['min_stock'] ? 'text-danger fw-semibold' : '' ?>"><?= fmt_num($p['qty_on_hand'], 0) ?> <small class="text-muted"><?= e($p['uom_code']) ?></small></td><td class="text-end"><?= fmt_idr($p['selling_price']) ?></td>
    <td class="small"><?= $p['requires_prescription'] ? '<span class="badge text-bg-danger" title="Wajib resep">Rx</span> ' : '' ?><?= $p['is_controlled'] ? '<span class="badge text-bg-dark" title="Terkontrol">CTL</span> ' : '' ?><?= $p['is_cold_chain'] ? '<span class="badge text-bg-info" title="Cold chain">2-8°</span>' : '' ?></td>
    <td><?= status_badge($p['status']) ?></td><td class="text-end text-nowrap"><a class="btn btn-xs btn-outline-secondary" href="<?= site_url('inventory/stock/card/' . $p['id']) ?>" title="Kartu stok"><i class="bi bi-card-list"></i></a> <?php if (can('master.product.edit')): ?><a class="btn btn-xs btn-outline-secondary" href="<?= site_url("master/products/{$p['id']}/edit") ?>" data-testid="product-edit-<?= $p['id'] ?>"><i class="bi bi-pencil"></i></a><?php endif; ?></td>
</tr><?php endforeach; ?><?php if (!$page->items): ?><tr><td colspan="10" class="text-center text-muted py-4">Tidak ada produk</td></tr><?php endif; ?>
</tbody></table></div><div class="card-footer py-1"><?php $this->load->view('partials/pagination', ['page' => $page]); ?></div></div>
