<?php $p = $product; ?>
<div class="erp-page-head"><div><h5 class="mb-0" data-testid="product-name"><?= e($p['name']) ?> <?= status_badge($p['status']) ?></h5><span class="font-monospace text-muted small"><?= e($p['sku']) ?> · <?= e($p['barcode']) ?></span></div>
<div class="d-flex gap-2"><a class="btn btn-sm btn-outline-secondary" href="<?= site_url('inventory/stock/card/' . $p['id']) ?>"><i class="bi bi-card-list me-1"></i>Kartu Stok</a>
<?php if (can('master.product.edit')): ?><a class="btn btn-sm btn-primary" href="<?= site_url("master/products/{$p['id']}/edit") ?>" data-testid="product-edit-btn"><i class="bi bi-pencil me-1"></i>Ubah</a>
<form method="post" action="<?= site_url("master/products/{$p['id']}/toggle") ?>" class="needs-confirm" data-confirm="Ubah status produk?"><?= csrf_field() ?><button class="btn btn-sm btn-outline-<?= $p['status'] === 'ACTIVE' ? 'danger' : 'success' ?>" data-testid="product-toggle-btn"><?= $p['status'] === 'ACTIVE' ? 'Nonaktifkan' : 'Aktifkan' ?></button></form><?php endif; ?></div></div>
<div class="row g-3">
<div class="col-lg-6"><div class="card erp-card h-100"><div class="card-header">Informasi</div><div class="card-body"><dl class="row small mb-0 erp-dl">
<?php foreach (['generic_name' => 'Generik', 'brand' => 'Brand', 'manufacturer_name' => 'Manufacturer', 'principal_name' => 'Principal', 'dosage_form' => 'Bentuk sediaan', 'strength' => 'Kekuatan', 'packaging' => 'Kemasan', 'purchase_price' => 'Harga beli', 'selling_price' => 'Harga jual', 'margin_pct' => 'Margin %', 'min_stock' => 'Stok min', 'reorder_point' => 'Reorder point', 'lead_time_days' => 'Lead time'] as $k => $l): ?>
<dt class="col-5"><?= $l ?></dt><dd class="col-7"><?= in_array($k, ['purchase_price', 'selling_price']) ? fmt_idr($p[$k]) : e($p[$k] ?? '-') ?></dd><?php endforeach; ?>
<dt class="col-5">Flag</dt><dd class="col-7"><?= $p['is_batch_tracked'] ? 'Batch ' : '' ?><?= $p['is_expiry_tracked'] ? '· Expiry ' : '' ?><?= $p['requires_prescription'] ? '· Rx ' : '' ?><?= $p['is_controlled'] ? '· Terkontrol ' : '' ?><?= $p['is_cold_chain'] ? "· Cold chain {$p['storage_min_temp']}–{$p['storage_max_temp']}°C" : '' ?></dd>
</dl>
<?php if ($p['units']): ?><h6 class="mt-3">Konversi Satuan</h6><table class="table table-sm erp-table small"><thead><tr><th>Satuan</th><th class="text-end">Faktor</th><th>Barcode</th><th class="text-end">Harga</th></tr></thead><tbody><?php foreach ($p['units'] as $u): ?><tr><td><?= e($u['uom_code']) ?></td><td class="text-end"><?= fmt_num($u['conversion_factor'], 0) ?></td><td><?= e($u['barcode']) ?></td><td class="text-end"><?= $u['selling_price'] !== null ? fmt_idr($u['selling_price']) : '-' ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?>
</div></div></div>
<div class="col-lg-6"><div class="card erp-card mb-3"><div class="card-header">Batch</div><table class="table table-sm erp-table mb-0 small" data-testid="product-batches"><thead><tr><th>No. Batch</th><th>ED</th><th class="text-end">Cost</th><th>Status</th></tr></thead><tbody>
<?php foreach ($batches as $b): ?><tr><td class="font-monospace"><?= e($b['batch_no']) ?></td><td class="<?= $b['expiry_date'] && $b['expiry_date'] < date('Y-m-d') ? 'text-danger fw-semibold' : '' ?>"><?= fmt_date($b['expiry_date']) ?></td><td class="text-end"><?= fmt_idr($b['unit_cost']) ?></td><td><?= status_badge($b['status']) ?></td></tr><?php endforeach; ?>
<?php if (!$batches): ?><tr><td colspan="4" class="text-muted text-center">Belum ada batch</td></tr><?php endif; ?></tbody></table></div>
<div class="card erp-card"><div class="card-header">Audit Trail</div><table class="table table-sm erp-table mb-0 small" data-testid="product-audit"><tbody><?php foreach ($audit as $a): ?><tr><td class="text-nowrap text-muted"><?= fmt_dt($a['created_at']) ?></td><td><?= e($a['username']) ?></td><td><code><?= e($a['action']) ?></code></td><td><a href="<?= site_url('audit/' . $a['id']) ?>">detail</a></td></tr><?php endforeach; ?></tbody></table></div></div>
</div>
