<?php $items = old('items', []); $errs = $this->session->flashdata('errors') ?: []; ?>
<form method="post" data-testid="transfer-form" class="erp-doc-form"><?= csrf_field() ?>
<div class="card erp-card mb-3"><div class="card-body row g-2">
    <div class="col-md-3"><label class="form-label">Gudang Asal *</label><select class="form-select form-select-sm" name="from_warehouse_id" id="warehouseSelect" required data-testid="trf-from"><option value="">—</option><?php foreach ($warehouses as $w): ?><option value="<?= $w['id'] ?>" <?= (string) old('from_warehouse_id') === (string) $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-3"><label class="form-label">Gudang Tujuan *</label><select class="form-select form-select-sm <?= isset($errs['to_warehouse_id']) ? 'is-invalid' : '' ?>" name="to_warehouse_id" required data-testid="trf-to"><option value="">—</option><?php foreach ($warehouses as $w): ?><option value="<?= $w['id'] ?>" <?= (string) old('to_warehouse_id') === (string) $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select><div class="invalid-feedback"><?= e($errs['to_warehouse_id'] ?? '') ?></div></div>
    <div class="col-md-2"><label class="form-label">Tanggal *</label><input class="form-control form-control-sm" type="date" name="transfer_date" value="<?= e(old('transfer_date', date('Y-m-d'))) ?>" required data-testid="trf-date"></div>
    <div class="col-md-4"><label class="form-label">Catatan</label><input class="form-control form-control-sm" name="notes" value="<?= e(old('notes')) ?>"></div>
</div></div>
<div class="card erp-card mb-3"><div class="card-header d-flex justify-content-between"><span>Item</span><small class="text-muted">Batch kosong = alokasi otomatis FEFO saat pengiriman.</small></div>
<div class="table-responsive"><table class="table table-sm erp-table mb-0 erp-items" id="itemsTable" data-testid="trf-items"><thead><tr><th style="width:40%">Produk *</th><th>Batch (opsional)</th><th class="text-end">Qty *</th><th>Catatan</th><th></th></tr></thead><tbody>
<?php foreach (array_merge($items, [[]]) as $i => $it): ?><tr>
    <td><input type="hidden" name="items[<?= $i ?>][product_id]" value="<?= e($it['product_id'] ?? '') ?>" class="js-product-id"><input class="form-control form-control-sm js-product-search" value="<?= e($it['product_label'] ?? '') ?>" placeholder="Cari produk…" autocomplete="off" data-testid="trf-item-product-<?= $i ?>"><input type="hidden" name="items[<?= $i ?>][product_label]" class="js-product-label"></td>
    <td><select class="form-select form-select-sm js-batch" name="items[<?= $i ?>][batch_id]" data-selected="<?= e($it['batch_id'] ?? '') ?>"><option value="">FEFO otomatis</option></select></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][qty_requested]" value="<?= e($it['qty_requested'] ?? '') ?>" inputmode="decimal" data-testid="trf-item-qty-<?= $i ?>"></td>
    <td><input class="form-control form-control-sm" name="items[<?= $i ?>][notes]" value="<?= e($it['notes'] ?? '') ?>"></td><td><button type="button" class="btn btn-xs btn-outline-danger row-remove"><i class="bi bi-x"></i></button></td></tr><?php endforeach; ?>
</tbody></table></div><div class="p-2"><button type="button" class="btn btn-xs btn-outline-secondary" data-add-row="#itemsTable" data-testid="trf-add-row"><i class="bi bi-plus"></i> Tambah baris</button><?php if (isset($errs['items'])): ?><span class="text-danger small ms-2"><?= e($errs['items']) ?></span><?php endif; ?></div></div>
<button class="btn btn-primary" data-testid="trf-save"><i class="bi bi-save me-1"></i>Simpan sebagai Draft</button> <a class="btn btn-link" href="<?= site_url('inventory/transfers') ?>">Batal</a>
</form>
