<?php $d = $doc; $canReceive = in_array('receive', $d['actions'], true) && can('inventory.transfer.post'); ?>
<div class="erp-page-head"><h5 class="mb-0 font-monospace" data-testid="trf-no"><?= e($d['transfer_no']) ?></h5><a class="btn btn-sm btn-link" href="<?= site_url('inventory/transfers') ?>">&larr; Daftar</a></div>
<?php $this->load->view('partials/workflow_panel', ['doc' => $d, 'base' => 'inventory/transfers', 'perms' => ['submit' => 'inventory.transfer.edit', 'approve' => 'inventory.transfer.approve', 'reject' => 'inventory.transfer.approve', 'cancel' => 'inventory.transfer.cancel', 'ship' => 'inventory.transfer.post']]); ?>
<div class="card erp-card mb-3"><div class="card-body"><dl class="row small mb-0"><dt class="col-2">Tanggal</dt><dd class="col-4"><?= fmt_date($d['transfer_date']) ?></dd><dt class="col-2">Rute</dt><dd class="col-4"><?= e($d['from_warehouse']['name']) ?> → <?= e($d['to_warehouse']['name']) ?></dd>
<dt class="col-2">Mutasi keluar</dt><dd class="col-4"><?= $d['out_movement_id'] ? '<a href="' . site_url('inventory/movements/' . $d['out_movement_id']) . '" data-testid="trf-out-link">#' . $d['out_movement_id'] . '</a>' : '-' ?></dd><dt class="col-2">Mutasi masuk</dt><dd class="col-4"><?= $d['in_movement_id'] ? '<a href="' . site_url('inventory/movements/' . $d['in_movement_id']) . '" data-testid="trf-in-link">#' . $d['in_movement_id'] . '</a>' : '-' ?></dd>
<dt class="col-2">Catatan</dt><dd class="col-10"><?= e($d['notes']) ?></dd></dl></div></div>
<form method="post" action="<?= site_url("inventory/transfers/{$d['id']}/action/receive") ?>" class="needs-confirm" data-confirm="Terima barang di gudang tujuan? Stok akan bertambah."><?= csrf_field() ?>
<div class="card erp-card"><table class="table table-sm erp-table mb-0" data-testid="trf-items-table"><thead><tr><th>#</th><th>Produk</th><th>Batch / ED</th><th class="text-end">Diminta</th><th class="text-end">Dikirim</th><th class="text-end">Diterima</th><th>Catatan</th></tr></thead><tbody>
<?php foreach ($d['items'] as $i): ?><tr><td><?= $i['line_no'] ?></td><td><?= e($i['product_name']) ?><br><small class="text-muted font-monospace"><?= e($i['sku']) ?></small></td><td class="small font-monospace"><?= e($i['batch_no'] ?? ($d['status'] === 'DRAFT' || $d['status'] === 'SUBMITTED' || $d['status'] === 'APPROVED' ? 'FEFO saat kirim' : '-')) ?> <span class="text-muted"><?= fmt_date($i['expiry_date']) ?></span></td>
<td class="text-end"><?= fmt_num($i['qty_requested'], 0) ?></td><td class="text-end"><?= fmt_num($i['qty_shipped'], 0) ?></td>
<td class="text-end" style="width:130px"><?php if ($canReceive): ?><input class="form-control form-control-sm text-end" name="received[<?= $i['id'] ?>]" value="<?= e($i['qty_shipped']) ?>" inputmode="decimal" data-testid="trf-received-<?= $i['id'] ?>"><?php else: echo fmt_num($i['qty_received'], 0); endif; ?></td><td class="small text-muted"><?= e($i['notes']) ?></td></tr><?php endforeach; ?></tbody></table>
<?php if ($canReceive): ?><div class="card-footer"><button class="btn btn-sm btn-success" data-testid="wf-action-receive"><i class="bi bi-box-arrow-in-down me-1"></i>Terima di Gudang Tujuan</button></div><?php endif; ?></div></form>
