<?php $d = $doc ?? []; $items = old('items', $d['items'] ?? []); $errs = $this->session->flashdata('errors') ?: []; ?>
<form method="post" data-testid="po-form" class="erp-doc-form"><?= csrf_field() ?>
<div class="card erp-card mb-3"><div class="card-body row g-2">
    <div class="col-md-4"><label class="form-label">Supplier *</label><select class="form-select form-select-sm <?= isset($errs['supplier_id']) ? 'is-invalid' : '' ?>" name="supplier_id" required data-testid="po-supplier"><option value="">—</option><?php foreach ($suppliers as $s): ?><option value="<?= $s['id'] ?>" <?= (string) old('supplier_id', $d['supplier_id'] ?? '') === (string) $s['id'] ? 'selected' : '' ?>><?= e($s['name']) ?></option><?php endforeach; ?></select><div class="invalid-feedback"><?= e($errs['supplier_id'] ?? '') ?></div></div>
    <div class="col-md-3"><label class="form-label">Gudang Penerima *</label><select class="form-select form-select-sm" name="warehouse_id" id="warehouseSelect" required data-testid="po-warehouse"><option value="">—</option><?php foreach ($warehouses as $w): ?><option value="<?= $w['id'] ?>" <?= (string) old('warehouse_id', $d['warehouse_id'] ?? '') === (string) $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-2"><label class="form-label">Tanggal PO *</label><input class="form-control form-control-sm" type="date" name="order_date" value="<?= e(old('order_date', $d['order_date'] ?? date('Y-m-d'))) ?>" required data-testid="po-date"></div>
    <div class="col-md-2"><label class="form-label">Perkiraan Datang</label><input class="form-control form-control-sm" type="date" name="expected_date" value="<?= e(old('expected_date', $d['expected_date'] ?? '')) ?>"></div>
    <div class="col-md-1"><label class="form-label">Tempo</label><input class="form-control form-control-sm text-end" name="payment_term_days" value="<?= e(old('payment_term_days', $d['payment_term_days'] ?? '0')) ?>" inputmode="numeric"></div>
    <input type="hidden" name="pr_id" value="<?= e(old('pr_id', $d['pr_id'] ?? $this->input->get('pr_id'))) ?>">
    <div class="col-12"><label class="form-label">Catatan</label><input class="form-control form-control-sm" name="notes" value="<?= e(old('notes', $d['notes'] ?? '')) ?>"></div>
</div></div>
<div class="card erp-card mb-3"><div class="card-header">Item</div>
<div class="table-responsive"><table class="table table-sm erp-table mb-0 erp-items" id="itemsTable" data-testid="po-items"><thead><tr><th style="width:34%">Produk *</th><th class="text-end">Qty *</th><th class="text-end">Harga Satuan</th><th class="text-end">Disk %</th><th class="text-end">Pajak %</th><th>Catatan</th><th></th></tr></thead><tbody>
<?php foreach (array_merge($items, [[]]) as $i => $it): ?><tr>
    <td><input type="hidden" name="items[<?= $i ?>][product_id]" value="<?= e($it['product_id'] ?? '') ?>" class="js-product-id"><input class="form-control form-control-sm js-product-search" value="<?= e(isset($it['product_name']) ? $it['sku'] . ' — ' . $it['product_name'] : ($it['product_label'] ?? '')) ?>" placeholder="Cari produk…" autocomplete="off" data-testid="po-item-product-<?= $i ?>"><input type="hidden" name="items[<?= $i ?>][product_label]" class="js-product-label"></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][qty_ordered]" value="<?= e($it['qty_ordered'] ?? '') ?>" inputmode="decimal" data-testid="po-item-qty-<?= $i ?>"></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][unit_price]" value="<?= e($it['unit_price'] ?? '') ?>" inputmode="decimal" data-testid="po-item-price-<?= $i ?>"></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][discount_pct]" value="<?= e($it['discount_pct'] ?? '') ?>" inputmode="decimal"></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][tax_pct]" value="<?= e($it['tax_pct'] ?? '') ?>" inputmode="decimal"></td>
    <td><input class="form-control form-control-sm" name="items[<?= $i ?>][notes]" value="<?= e($it['notes'] ?? '') ?>"></td><td><button type="button" class="btn btn-xs btn-outline-danger row-remove"><i class="bi bi-x"></i></button></td></tr><?php endforeach; ?>
</tbody></table></div><div class="p-2"><button type="button" class="btn btn-xs btn-outline-secondary" data-add-row="#itemsTable" data-testid="po-add-row"><i class="bi bi-plus"></i> Tambah baris</button><?php if (isset($errs['items'])): ?><span class="text-danger small ms-2"><?= e($errs['items']) ?></span><?php endif; ?></div></div>
<button class="btn btn-primary" data-testid="po-save"><i class="bi bi-save me-1"></i>Simpan sebagai Draft</button> <a class="btn btn-link" href="<?= site_url('purchasing/orders') ?>">Batal</a>
</form>
