<?php $d = $doc; ?>
<div class="erp-page-head"><h5 class="mb-0 font-monospace" data-testid="po-no"><?= e($d['po_no']) ?></h5><a class="btn btn-sm btn-link" href="<?= site_url('purchasing/orders') ?>">&larr; Daftar</a></div>
<?php $this->load->view('partials/workflow_panel', ['doc' => $d, 'base' => 'purchasing/orders', 'editUrl' => "purchasing/orders/{$d['id']}/edit",
    'perms' => ['submit' => 'purchasing.po.edit', 'edit' => 'purchasing.po.edit', 'approve' => 'purchasing.po.approve', 'reject' => 'purchasing.po.approve', 'cancel' => 'purchasing.po.cancel', 'order' => 'purchasing.po.post', 'close' => 'purchasing.po.edit']]); ?>
<div class="card erp-card mb-3"><div class="card-body"><dl class="row small mb-0">
<dt class="col-2">Supplier</dt><dd class="col-4"><?= e($d['supplier']['name'] ?? '-') ?></dd><dt class="col-2">Gudang</dt><dd class="col-4"><?= e($d['warehouse']['name'] ?? '-') ?></dd>
<dt class="col-2">Tanggal PO</dt><dd class="col-4"><?= fmt_date($d['order_date']) ?></dd><dt class="col-2">Perkiraan datang</dt><dd class="col-4"><?= fmt_date($d['expected_date']) ?></dd>
<dt class="col-2">Tempo</dt><dd class="col-4"><?= (int) $d['payment_term_days'] ?> hari</dd><dt class="col-2">Catatan</dt><dd class="col-4"><?= e($d['notes']) ?></dd>
<?php if ($d['rejection_reason']): ?><dt class="col-2 text-danger">Alasan tolak</dt><dd class="col-10 text-danger"><?= e($d['rejection_reason']) ?></dd><?php endif; ?></dl></div></div>
<?php if (in_array($d['status'], ['ORDERED', 'PARTIAL'], true) && can('purchasing.gr.create')): ?><a class="btn btn-sm btn-outline-primary mb-3" href="<?= site_url('purchasing/receipts/create?po_id=' . $d['id']) ?>" data-testid="po-to-gr"><i class="bi bi-box-arrow-in-down me-1"></i>Terima Barang (GR) untuk PO ini</a><?php endif; ?>
<div class="card erp-card"><table class="table table-sm erp-table mb-0" data-testid="po-items-table"><thead><tr><th>#</th><th>Produk</th><th class="text-end">Qty Pesan</th><th class="text-end">Diterima</th><th class="text-end">Harga</th><th class="text-end">Disk%</th><th class="text-end">Pajak%</th><th class="text-end">Total Baris</th></tr></thead><tbody>
<?php foreach ($d['items'] as $i): ?><tr><td><?= $i['line_no'] ?></td><td><?= e($i['product_name']) ?><br><small class="text-muted font-monospace"><?= e($i['sku']) ?></small></td><td class="text-end"><?= fmt_num($i['qty_ordered'], 0) ?></td><td class="text-end <?= (float) $i['qty_received'] >= (float) $i['qty_ordered'] ? 'text-success' : ((float) $i['qty_received'] > 0 ? 'text-warning' : '') ?>"><?= fmt_num($i['qty_received'], 0) ?></td><td class="text-end small"><?= fmt_idr($i['unit_price']) ?></td><td class="text-end small"><?= fmt_num($i['discount_pct'], 2) ?></td><td class="text-end small"><?= fmt_num($i['tax_pct'], 2) ?></td><td class="text-end"><?= fmt_idr($i['line_total']) ?></td></tr><?php endforeach; ?></tbody>
<tfoot><tr><th colspan="7" class="text-end">Subtotal</th><th class="text-end"><?= fmt_idr($d['subtotal']) ?></th></tr><tr><th colspan="7" class="text-end">Diskon</th><th class="text-end">-<?= fmt_idr($d['discount_total']) ?></th></tr><tr><th colspan="7" class="text-end">Pajak</th><th class="text-end"><?= fmt_idr($d['tax_total']) ?></th></tr><tr><th colspan="7" class="text-end">Grand Total</th><th class="text-end" data-testid="po-grand-total"><?= fmt_idr($d['grand_total']) ?></th></tr></tfoot></table></div>
