<?php $s = $supplier; ?>
<div class="erp-page-head"><h5 class="mb-0"><?= e($s['name']) ?> <small class="text-muted font-monospace">(<?= e($s['code']) ?>)</small></h5><div><?php if (can('purchasing.supplier.edit')): ?><a class="btn btn-sm btn-outline-secondary" href="<?= site_url('purchasing/suppliers/' . $s['id'] . '/edit') ?>" data-testid="sup-edit"><i class="bi bi-pencil me-1"></i>Ubah</a><?php endif; ?> <a class="btn btn-sm btn-link" href="<?= site_url('purchasing/suppliers') ?>">&larr; Daftar</a></div></div>
<div class="card erp-card mb-3"><div class="card-body"><dl class="row small mb-0">
<dt class="col-2">Tipe</dt><dd class="col-4"><?= e($s['supplier_type']) ?></dd><dt class="col-2">Status</dt><dd class="col-4"><?= status_badge($s['is_active'] ? 'ACTIVE' : 'INACTIVE') ?></dd>
<dt class="col-2">NPWP</dt><dd class="col-4"><?= e($s['npwp'] ?: '-') ?></dd><dt class="col-2">No. Izin</dt><dd class="col-4"><?= e($s['license_no'] ?: '-') ?></dd>
<dt class="col-2">Kontak</dt><dd class="col-4"><?= e($s['contact_person'] ?: '-') ?> <?= $s['phone'] ? '· ' . e($s['phone']) : '' ?></dd><dt class="col-2">Email</dt><dd class="col-4"><?= e($s['email'] ?: '-') ?></dd>
<dt class="col-2">Tempo</dt><dd class="col-4"><?= (int) $s['payment_term_days'] ?> hari</dd><dt class="col-2">Alamat</dt><dd class="col-4"><?= e($s['address'] ?: '-') ?></dd></dl></div></div>
<div class="row g-3"><div class="col-lg-6"><div class="card erp-card"><div class="card-header py-1 small fw-semibold">Katalog Produk</div>
<table class="table table-sm erp-table mb-0" data-testid="sup-catalog"><thead><tr><th>Produk</th><th class="text-end">Harga Terakhir</th><th class="text-end">Lead time</th></tr></thead><tbody>
<?php foreach ($s['catalog'] as $c): ?><tr><td class="small"><?= e($c['product_name']) ?><br><span class="text-muted font-monospace"><?= e($c['sku']) ?></span></td><td class="text-end small"><?= fmt_idr($c['last_price']) ?></td><td class="text-end small"><?= (int) $c['lead_time_days'] ?> hr</td></tr><?php endforeach; ?>
<?php if (!$s['catalog']): ?><tr><td colspan="3" class="text-center text-muted py-3">Belum ada katalog</td></tr><?php endif; ?></tbody></table></div></div>
<div class="col-lg-6"><div class="card erp-card"><div class="card-header py-1 small fw-semibold">Riwayat Harga Beli</div>
<table class="table table-sm erp-table mb-0" data-testid="sup-price-history"><thead><tr><th>Tanggal</th><th>Produk</th><th class="text-end">Harga</th><th>Ref</th></tr></thead><tbody>
<?php foreach ($s['price_history'] as $h): ?><tr><td class="small"><?= fmt_date($h['effective_date']) ?></td><td class="small font-monospace"><?= e($h['sku']) ?></td><td class="text-end small"><?= fmt_idr($h['price']) ?><?php if ($h['po_price'] !== null && (float) $h['po_price'] !== (float) $h['price']): ?> <span class="badge text-bg-warning" title="Varian dari harga PO <?= fmt_idr($h['po_price']) ?>">varian</span><?php endif; ?></td><td class="small text-muted"><?= e($h['source_ref_no'] ?: $h['source_ref_type']) ?></td></tr><?php endforeach; ?>
<?php if (!$s['price_history']): ?><tr><td colspan="4" class="text-center text-muted py-3">Belum ada riwayat</td></tr><?php endif; ?></tbody></table></div></div></div>
