<?php $d = $doc ?? []; $items = old('items', $d['items'] ?? []); $errs = $this->session->flashdata('errors') ?: []; ?>
<form method="post" data-testid="prt-form" class="erp-doc-form"><?= csrf_field() ?>
<div class="card erp-card mb-3"><div class="card-body row g-2">
    <div class="col-md-4"><label class="form-label">Supplier *</label><select class="form-select form-select-sm <?= isset($errs['supplier_id']) ? 'is-invalid' : '' ?>" name="supplier_id" required data-testid="prt-supplier"><option value="">—</option><?php foreach ($suppliers as $s): ?><option value="<?= $s['id'] ?>" <?= (string) old('supplier_id', $d['supplier_id'] ?? '') === (string) $s['id'] ? 'selected' : '' ?>><?= e($s['name']) ?></option><?php endforeach; ?></select><div class="invalid-feedback"><?= e($errs['supplier_id'] ?? '') ?></div></div>
    <div class="col-md-3"><label class="form-label">Gudang Asal *</label><select class="form-select form-select-sm" name="warehouse_id" id="warehouseSelect" required data-testid="prt-warehouse"><option value="">—</option><?php foreach ($warehouses as $w): ?><option value="<?= $w['id'] ?>" <?= (string) old('warehouse_id', $d['warehouse_id'] ?? '') === (string) $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-2"><label class="form-label">Tanggal *</label><input class="form-control form-control-sm" type="date" name="return_date" value="<?= e(old('return_date', $d['return_date'] ?? date('Y-m-d'))) ?>" required data-testid="prt-date"></div>
    <div class="col-md-3"><label class="form-label">Alasan Retur *</label><select class="form-select form-select-sm <?= isset($errs['reason_code_id']) ? 'is-invalid' : '' ?>" name="reason_code_id" required data-testid="prt-reason"><option value="">—</option><?php foreach ($reasons as $r): ?><option value="<?= $r['id'] ?>" <?= (string) old('reason_code_id', $d['reason_code_id'] ?? '') === (string) $r['id'] ? 'selected' : '' ?>><?= e($r['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-12"><label class="form-label">Catatan</label><input class="form-control form-control-sm" name="notes" value="<?= e(old('notes', $d['notes'] ?? '')) ?>"></div>
</div></div>
<div class="card erp-card mb-3"><div class="card-header d-flex justify-content-between"><span>Item Retur</span><small class="text-muted">Pilih batch untuk produk batch-tracked. Stok berkurang saat posting.</small></div>
<div class="table-responsive"><table class="table table-sm erp-table mb-0 erp-items" id="itemsTable" data-testid="prt-items"><thead><tr><th style="width:34%">Produk *</th><th>Batch</th><th class="text-end">Qty *</th><th class="text-end">Harga</th><th>Catatan</th><th></th></tr></thead><tbody>
<?php foreach (array_merge($items, [[]]) as $i => $it): ?><tr>
    <td><input type="hidden" name="items[<?= $i ?>][product_id]" value="<?= e($it['product_id'] ?? '') ?>" class="js-product-id"><input class="form-control form-control-sm js-product-search" value="<?= e(isset($it['product_name']) ? $it['sku'] . ' — ' . $it['product_name'] : ($it['product_label'] ?? '')) ?>" placeholder="Cari produk…" autocomplete="off" data-testid="prt-item-product-<?= $i ?>"><input type="hidden" name="items[<?= $i ?>][product_label]" class="js-product-label"></td>
    <td><select class="form-select form-select-sm js-batch" name="items[<?= $i ?>][batch_id]" data-selected="<?= e($it['batch_id'] ?? '') ?>"><option value="">(tanpa batch)</option><?php if (!empty($it['batch_id'])): ?><option value="<?= $it['batch_id'] ?>" selected><?= e($it['batch_no'] ?? $it['batch_id']) ?></option><?php endif; ?></select></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][qty]" value="<?= e($it['qty'] ?? '') ?>" inputmode="decimal" data-testid="prt-item-qty-<?= $i ?>"></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][unit_cost]" value="<?= e($it['unit_cost'] ?? '') ?>" inputmode="decimal" placeholder="avg cost"></td>
    <td><input class="form-control form-control-sm" name="items[<?= $i ?>][notes]" value="<?= e($it['notes'] ?? '') ?>"></td><td><button type="button" class="btn btn-xs btn-outline-danger row-remove"><i class="bi bi-x"></i></button></td></tr><?php endforeach; ?>
</tbody></table></div><div class="p-2"><button type="button" class="btn btn-xs btn-outline-secondary" data-add-row="#itemsTable" data-testid="prt-add-row"><i class="bi bi-plus"></i> Tambah baris</button><?php if (isset($errs['items'])): ?><span class="text-danger small ms-2"><?= e($errs['items']) ?></span><?php endif; ?></div></div>
<button class="btn btn-primary" data-testid="prt-save"><i class="bi bi-save me-1"></i>Simpan sebagai Draft</button> <a class="btn btn-link" href="<?= site_url('purchasing/returns') ?>">Batal</a>
</form>
