<?php /** Generic list untuk dokumen procurement (PR/PO/GR/Return): $page, $base, $title_new, $perm, $testid, $statuses, $with_supplier */ ?>
<div class="erp-page-head"><form class="erp-filter" method="get"><input class="form-control form-control-sm" name="q" value="<?= e($_GET['q'] ?? '') ?>" placeholder="No. dokumen">
    <select class="form-select form-select-sm" name="status"><option value="">Semua status</option><?php foreach ($statuses as $s): ?><option <?= ($_GET['status'] ?? '') === $s ? 'selected' : '' ?>><?= $s ?></option><?php endforeach; ?></select><button class="btn btn-sm btn-outline-secondary">Filter</button></form>
    <?php if (can("$perm.create")): ?><a class="btn btn-sm btn-primary" href="<?= site_url("$base/create") ?>" data-testid="<?= $testid ?>-create-btn"><i class="bi bi-plus-lg me-1"></i><?= e($title_new) ?></a><?php endif; ?></div>
<div class="card erp-card"><table class="table table-sm table-hover erp-table mb-0" data-testid="<?= $testid ?>-table"><thead><tr><th><?= sort_link('doc_no', 'No. Dokumen') ?></th><th><?= sort_link('doc_date', 'Tanggal') ?></th><?php if (!empty($with_supplier)): ?><th>Supplier</th><th class="text-end">Total</th><?php endif; ?><th>Catatan</th><th>Dibuat oleh</th><th><?= sort_link('status', 'Status') ?></th></tr></thead><tbody>
<?php foreach ($page->items as $d): ?><tr data-testid="<?= $testid ?>-row-<?= $d['id'] ?>"><td><a class="font-monospace" href="<?= site_url("$base/{$d['id']}") ?>"><?= e($d['doc_no']) ?></a></td><td class="small"><?= fmt_date($d['doc_date']) ?></td>
<?php if (!empty($with_supplier)): ?><td class="small"><?= e($d['supplier_name'] ?? '-') ?></td><td class="text-end small"><?= isset($d['grand_total']) ? fmt_idr($d['grand_total']) : '-' ?></td><?php endif; ?>
<td class="small text-muted text-truncate" style="max-width:240px"><?= e($d['notes']) ?></td><td class="small"><?= e($d['created_by_name']) ?></td><td><?= status_badge($d['status']) ?></td></tr><?php endforeach; ?>
<?php if (!$page->items): ?><tr><td colspan="<?= !empty($with_supplier) ? 7 : 5 ?>" class="text-center text-muted py-4">Belum ada dokumen</td></tr><?php endif; ?></tbody></table><div class="card-footer py-1"><?php $this->load->view('partials/pagination', ['page' => $page]); ?></div></div>
