<?php $d = $doc; $counting = $d['status'] === 'COUNTING' && can('inventory.opname.edit'); ?>
<div class="erp-page-head"><h5 class="mb-0 font-monospace" data-testid="opn-no"><?= e($d['opname_no']) ?> <small class="text-muted fw-normal"><?= e($d['warehouse']['name']) ?> · <?= fmt_date($d['opname_date']) ?> · <?= $d['opname_type'] ?></small></h5><a class="btn btn-sm btn-link" href="<?= site_url('inventory/opnames') ?>">&larr; Daftar</a></div>
<?php $this->load->view('partials/workflow_panel', ['doc' => $d, 'base' => 'inventory/opnames', 'perms' => ['start' => 'inventory.opname.edit', 'submit' => 'inventory.opname.edit', 'approve' => 'inventory.opname.approve', 'reject' => 'inventory.opname.approve', 'cancel' => 'inventory.opname.cancel', 'post' => 'inventory.opname.post']]); ?>
<?php if ($d['movement_id']): ?><p class="small">Mutasi selisih: <a href="<?= site_url('inventory/movements/' . $d['movement_id']) ?>" data-testid="opn-movement-link">#<?= $d['movement_id'] ?></a></p><?php endif; ?>
<form method="post" action="<?= site_url("inventory/opnames/{$d['id']}/count") ?>"><?= csrf_field() ?>
<div class="card erp-card"><table class="table table-sm erp-table mb-0" data-testid="opn-items-table"><thead><tr><th>Produk</th><th>Batch / ED</th><th>Lokasi</th><th>Kondisi</th><th class="text-end">Qty Sistem</th><th class="text-end">Qty Hitung</th><th class="text-end">Selisih</th><th class="text-end">Nilai Selisih</th></tr></thead><tbody>
<?php $tot = 0; foreach ($d['items'] as $i): $tot += $i['qty_variance'] * $i['unit_cost']; ?><tr><td><?= e($i['product_name']) ?><br><small class="text-muted font-monospace"><?= e($i['sku']) ?></small></td><td class="small font-monospace"><?= e($i['batch_no'] ?? '-') ?> <span class="text-muted"><?= fmt_date($i['expiry_date']) ?></span></td><td class="small"><?= e($i['location_code']) ?></td><td><?= status_badge($i['condition_code']) ?></td>
<td class="text-end"><?= fmt_num($i['qty_system'], 0) ?></td><td class="text-end" style="width:130px"><?php if ($counting): ?><input class="form-control form-control-sm text-end" name="counts[<?= $i['id'] ?>]" value="<?= e($i['qty_counted']) ?>" inputmode="decimal" data-testid="opn-count-<?= $i['id'] ?>"><?php else: echo $i['qty_counted'] !== null ? fmt_num($i['qty_counted'], 0) : '<span class="text-muted">belum</span>'; endif; ?></td>
<td class="text-end fw-semibold <?= $i['qty_variance'] < 0 ? 'text-danger' : ($i['qty_variance'] > 0 ? 'text-success' : '') ?>"><?= $i['qty_counted'] !== null ? fmt_num($i['qty_variance'], 0) : '' ?></td><td class="text-end small"><?= $i['qty_counted'] !== null ? fmt_idr($i['qty_variance'] * $i['unit_cost']) : '' ?></td></tr><?php endforeach; ?>
<?php if (!$d['items']): ?><tr><td colspan="8" class="text-center text-muted py-4">Snapshot dibuat saat "Mulai Hitung"</td></tr><?php endif; ?></tbody>
<?php if ($d['items']): ?><tfoot><tr class="table-light"><th colspan="7" class="text-end">Total nilai selisih</th><th class="text-end" data-testid="opn-total-variance"><?= fmt_idr($tot) ?></th></tr></tfoot><?php endif; ?></table>
<?php if ($counting): ?><div class="card-footer"><button class="btn btn-sm btn-primary" data-testid="opn-save-counts"><i class="bi bi-save me-1"></i>Simpan Hasil Hitung</button></div><?php endif; ?></div></form>
