<?php $d = $doc ?? []; $items = old('items', $d['items'] ?? []); $errs = $this->session->flashdata('errors') ?: []; ?>
<form method="post" data-testid="adjustment-form" class="erp-doc-form"><?= csrf_field() ?>
<div class="card erp-card mb-3"><div class="card-body row g-2">
    <div class="col-md-3"><label class="form-label">Gudang *</label><select class="form-select form-select-sm" name="warehouse_id" id="warehouseSelect" required <?= $d ? 'disabled' : '' ?> data-testid="adj-warehouse"><option value="">—</option><?php foreach ($warehouses as $w): ?><option value="<?= $w['id'] ?>" <?= (string) old('warehouse_id', $d['warehouse_id'] ?? '') === (string) $w['id'] ? 'selected' : '' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select><?php if ($d): ?><input type="hidden" name="warehouse_id" value="<?= $d['warehouse_id'] ?>"><?php endif; ?></div>
    <div class="col-md-2"><label class="form-label">Tanggal *</label><input class="form-control form-control-sm" type="date" name="adjustment_date" value="<?= e(old('adjustment_date', $d['adjustment_date'] ?? date('Y-m-d'))) ?>" required data-testid="adj-date"></div>
    <div class="col-md-3"><label class="form-label">Alasan *</label><select class="form-select form-select-sm <?= isset($errs['reason_code_id']) ? 'is-invalid' : '' ?>" name="reason_code_id" required data-testid="adj-reason"><option value="">—</option><?php foreach ($reasons as $r): ?><option value="<?= $r['id'] ?>" <?= (string) old('reason_code_id', $d['reason_code_id'] ?? '') === (string) $r['id'] ? 'selected' : '' ?>><?= e($r['name']) ?><?= $r['requires_note'] ? ' (wajib catatan)' : '' ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label">Catatan</label><input class="form-control form-control-sm <?= isset($errs['notes']) ? 'is-invalid' : '' ?>" name="notes" value="<?= e(old('notes', $d['notes'] ?? '')) ?>" data-testid="adj-notes"><div class="invalid-feedback"><?= e($errs['notes'] ?? '') ?></div></div>
</div></div>
<div class="card erp-card mb-3"><div class="card-header d-flex justify-content-between"><span>Item</span><small class="text-muted">Qty positif = tambah, negatif = kurang. Ketik nama/SKU/scan barcode.</small></div>
<div class="table-responsive"><table class="table table-sm erp-table mb-0 erp-items" id="itemsTable" data-testid="adj-items"><thead><tr><th style="width:32%">Produk *</th><th>Batch</th><th>Kondisi</th><th class="text-end">Qty *</th><th class="text-end">Harga Satuan</th><th>Catatan</th><th></th></tr></thead><tbody>
<?php foreach (array_merge($items, [[]]) as $i => $it): ?><tr>
    <td><input type="hidden" name="items[<?= $i ?>][product_id]" value="<?= e($it['product_id'] ?? '') ?>" class="js-product-id"><input class="form-control form-control-sm js-product-search" value="<?= e(isset($it['product_name']) ? $it['sku'] . ' — ' . $it['product_name'] : ($it['product_label'] ?? '')) ?>" placeholder="Cari produk…" autocomplete="off" data-testid="adj-item-product-<?= $i ?>"><input type="hidden" name="items[<?= $i ?>][product_label]" class="js-product-label"></td>
    <td><select class="form-select form-select-sm js-batch" name="items[<?= $i ?>][batch_id]" data-selected="<?= e($it['batch_id'] ?? '') ?>"><option value="">(otomatis/tanpa batch)</option><?php if (!empty($it['batch_id'])): ?><option value="<?= $it['batch_id'] ?>" selected><?= e($it['batch_no'] ?? $it['batch_id']) ?></option><?php endif; ?></select></td>
    <td><select class="form-select form-select-sm" name="items[<?= $i ?>][condition_code]"><?php foreach ($conditions as $c): ?><option <?= ($it['condition_code'] ?? 'GOOD') === $c ? 'selected' : '' ?>><?= $c ?></option><?php endforeach; ?></select></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][qty_change]" value="<?= e($it['qty_change'] ?? '') ?>" inputmode="decimal" data-testid="adj-item-qty-<?= $i ?>"></td>
    <td><input class="form-control form-control-sm text-end" name="items[<?= $i ?>][unit_cost]" value="<?= e($it['unit_cost'] ?? '') ?>" inputmode="decimal" placeholder="avg cost"></td>
    <td><input class="form-control form-control-sm" name="items[<?= $i ?>][notes]" value="<?= e($it['notes'] ?? '') ?>"></td><td><button type="button" class="btn btn-xs btn-outline-danger row-remove"><i class="bi bi-x"></i></button></td></tr><?php endforeach; ?>
</tbody></table></div><div class="p-2"><button type="button" class="btn btn-xs btn-outline-secondary" data-add-row="#itemsTable" data-testid="adj-add-row"><i class="bi bi-plus"></i> Tambah baris</button> <?php if (isset($errs['items'])): ?><span class="text-danger small ms-2"><?= e($errs['items']) ?></span><?php endif; ?></div></div>
<button class="btn btn-primary" data-testid="adj-save"><i class="bi bi-save me-1"></i>Simpan sebagai Draft</button> <a class="btn btn-link" href="<?= site_url('inventory/adjustments') ?>">Batal</a>
</form>
