<?php $d = $doc; ?>
<div class="erp-page-head"><h5 class="mb-0 font-monospace" data-testid="adj-no"><?= e($d['adjustment_no']) ?></h5><a class="btn btn-sm btn-link" href="<?= site_url('inventory/adjustments') ?>">&larr; Daftar</a></div>
<?php $this->load->view('partials/workflow_panel', ['doc' => $d, 'base' => 'inventory/adjustments', 'editUrl' => "inventory/adjustments/{$d['id']}/edit",
    'perms' => ['submit' => 'inventory.adjustment.edit', 'edit' => 'inventory.adjustment.edit', 'approve' => 'inventory.adjustment.approve', 'reject' => 'inventory.adjustment.approve', 'cancel' => 'inventory.adjustment.cancel', 'post' => 'inventory.adjustment.post']]); ?>
<div class="card erp-card mb-3"><div class="card-body"><dl class="row small mb-0"><dt class="col-2">Tanggal</dt><dd class="col-4"><?= fmt_date($d['adjustment_date']) ?></dd><dt class="col-2">Gudang</dt><dd class="col-4"><?= e($d['items'][0]['location_code'] ?? '') ?> (ID <?= $d['warehouse_id'] ?>)</dd>
<dt class="col-2">Catatan</dt><dd class="col-4"><?= e($d['notes']) ?></dd><dt class="col-2">Mutasi</dt><dd class="col-4"><?= $d['movement_id'] ? '<a href="' . site_url('inventory/movements/' . $d['movement_id']) . '" data-testid="adj-movement-link">#' . $d['movement_id'] . '</a>' : '-' ?></dd>
<?php if ($d['rejection_reason']): ?><dt class="col-2 text-danger">Alasan tolak</dt><dd class="col-10 text-danger"><?= e($d['rejection_reason']) ?></dd><?php endif; ?></dl></div></div>
<div class="card erp-card"><table class="table table-sm erp-table mb-0" data-testid="adj-items-table"><thead><tr><th>#</th><th>Produk</th><th>Batch / ED</th><th>Kondisi</th><th class="text-end">Qty</th><th class="text-end">Harga</th><th class="text-end">Nilai</th><th>Catatan</th></tr></thead><tbody>
<?php foreach ($d['items'] as $i): ?><tr><td><?= $i['line_no'] ?></td><td><?= e($i['product_name']) ?><br><small class="text-muted font-monospace"><?= e($i['sku']) ?></small></td><td class="small font-monospace"><?= e($i['batch_no'] ?? '-') ?> <span class="text-muted"><?= fmt_date($i['expiry_date']) ?></span></td><td><?= status_badge($i['condition_code']) ?></td>
<td class="text-end fw-semibold <?= $i['qty_change'] < 0 ? 'text-danger' : 'text-success' ?>"><?= ($i['qty_change'] > 0 ? '+' : '') . fmt_num($i['qty_change'], 0) ?> <small class="text-muted"><?= e($i['uom_code']) ?></small></td><td class="text-end small"><?= fmt_idr($i['unit_cost']) ?></td><td class="text-end small"><?= fmt_idr($i['qty_change'] * $i['unit_cost']) ?></td><td class="small text-muted"><?= e($i['notes']) ?></td></tr><?php endforeach; ?></tbody></table></div>
